=== Odenthma/WBA2_P2/geocatching/src/CacheList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/CacheList" xmlns:tns="http://www.example.org/CacheList" elementFormDefault="qualified">

<!--  
TODO:
use:required wann und wo?
alle name -> kamelSchreibWeise


 -->
 
 
 
<!-- cachelist 
	cache -->

<xsd:element name="CacheList" type="CacheListType"/>

<xsd:complexType name="CacheListType">
	<xsd:element name="Cache" type="CacheType">
		<xsd:complexType>
        	<xsd:attribute name="c_id" type="cIdRestriction"/> 
        </xsd:complexType>
	</xsd:element>
</xsd:complexType>

<xsd:simpleType name="cIdRestriction">
	<xsd:restriction base="xsd:token"> 
		<xsd:pattern value="[c][0-9]{4}"/> <!--  nur c+4stellige zahl -->
    </xsd:restriction> 
</xsd:simpleType>

<xsd:simpleType name="bIdRestriction">
	<xsd:restriction base="xsd:token"> 
		<xsd:pattern value="[b][0-9]{4}"/> <!--  nur c+4stellige zahl -->
    </xsd:restriction> 
</xsd:simpleType>

<xsd:simpleType name="lIdRestriction">
	<xsd:restriction base="xsd:token"> 
		<xsd:pattern value="[l][0-9]{4}"/> <!--  nur c+4stellige zahl -->
    </xsd:restriction> 
</xsd:simpleType>

<xsd:simpleType name="kIdRestriction">
	<xsd:restriction base="xsd:token"> 
		<xsd:pattern value="[k][0-9]{4}"/> <!--  nur c+4stellige zahl -->
    </xsd:restriction> 
</xsd:simpleType>


<!--  cache
	location
	name
	datum
	typ
	owner
	parkplatz
	informationen
	logs
	kommentare -->       
	
<xsd:complexType name="CacheType">
	<xsd:sequence>
		<xsd:element name="location">
			<xsd:complexType>
        		<xsd:attribute name="lat" type="latRestriction"/>
        		<xsd:attribute name="lon" type="lonRestriction"/>
   			</xsd:complexType>
		</xsd:element> 
		<xsd:element name="Name" type="xsd:string"/>
		<xsd:element name="Datum" type="dateRestriction"/>
		<xsd:element name="Typ" type="cacheTypeEnum"/>
		<xsd:element name="Owner" type="xsd:string">
			<xs:complexType>
    			<xs:attribute name="b_id" type="bIdRestriction" />
    		</xs:complexType>
    	</xsd:element>
		<xsd:element name="Parkplatz" type="xsd:string">
			<xsd:complexType>
        		<xsd:attribute name="lat" type="latRestriction"/>
        		<xsd:attribute name="lon" type="lonRestriction"/>
   			</xsd:complexType>
		</xsd:element>
		<xsd:element name="Informationen" type="InformationenType"/>
		<xsd:element name="Logs" type="LogsType"/>
		<xsd:element name="Kommentare" type="KommentareType"/>
	</xsd:sequence>
	<!-- <xsd:attribute name"c_id" type="cType" use="required"/> -->
</xsd:complexType>

<xsd:simpleType name="latRestriction">
	<xsd:restriction base="xsd:decimal"> 
		<xsd:pattern value="[\d]{1,2}\.[\d]{0,6}"/> <!-- kein minus, 1-2 zeichen vor punkt, 0-6 nach punkt -->
    </xsd:restriction> 
</xsd:simpleType>

<xsd:simpleType name="lonRestriction">
	<xsd:restriction base="xsd:decimal"> 
		<xsd:pattern value="-?[\d]{1,3}\.[\d]{0,6}"/> <!-- optionales minus, 1-3 zeichen vor punkt, 0-6 nach punkt -->
    </xsd:restriction> 
</xsd:simpleType>
   
<xsd:simpleType name="dateRestriction">
	<xsd:restriction base="xsd:decimal"> 
		<xsd:pattern value=" [0-9]{1,2}\.[0-9]{1,2}\.[0-9]{4}"/> <!-- kein minus, 1-2 zeichen vor punkt, 0-6 nach punkt -->
    </xsd:restriction> 
</xsd:simpleType>
  
<xs:simpleType name="cacheTypeEnum">
	<xs:restriction base="xs:string">
		<xs:enumeration value="Traditional Cache" />
		<xs:enumeration value="Multi Cache" />
		<xs:enumeration value="Puzzle Cache" />
		<xs:enumeration value="Mystery Cache" />
		<xs:enumeration value="Unknown Cache" />
	</xs:restriction>
</xs:simpleType>

<!-- <xsd:simpleType name="cType">
	<xsd:restriction base="xsd:string">
		<xs:pattern value="[c][0-9][0-9][0-+9][0-9]"/>
		<xs:Length value="5"/>
	</xsd:restriction>
</xsd:simpleType> -->

<!-- informationen
	schwierigkeit
	terrain
	land
	Bundesland
	provinz
	beschreibung_klein
	beschreibung_lang
	Hinweise
	geschätze_zeit
	Travelbug -->
	
<xsd:complexType name="InformationenType">
	<xsd:sequence>
		<xsd:element name="Schwierigkeit" type="doubleValueEnum"/>
		<xsd:element name="Terrain" type="doubleValueEnum"/>
		<xsd:element name="Land" type="xsd:string"/>
		<xsd:element name="Bundesland" typ="bundesLandEnum"/>
		<xsd:element name="Provinz" type="xsd:string"/>
		<xsd:element name="BeschreibungKlein" type="xsd:string"/>
		<xsd:element name="BeschreibungGross" type="xsd:string"/>
		<xsd:element name="Hinweise" type="xsd:string"/>
		<xsd:element name="GeschaetzteZeit" type="decimal"/>
		<xsd:element name="TravelBug" type="yesNoEnum"/>
	</xsd:sequence>
</xsd:complexType>

<xs:simpleType name="doubleValueEnum">
	<xs:restriction base="xs:double">
		<xs:enumeration value="1.0" />
		<xs:enumeration value="1.5" />
		<xs:enumeration value="2.0" />
		<xs:enumeration value="2.5" />
		<xs:enumeration value="3.0" />
		<xs:enumeration value="3.5" />
		<xs:enumeration value="4.0" />
		<xs:enumeration value="4.5" />
		<xs:enumeration value="5.0" />
	</xs:restriction>
</xs:simpleType>

<xsd:simpleType name="bundeslandEnum">
    <xsd:restriction base="xsd:string">
    	<xsd:enumeration value="Baden-Württemberg"/>
 		<xsd:enumeration value="Bayern"/>
 		<xsd:enumeration value="Berlin"/>
		<xsd:enumeration value="Brandenburg"/>
 		<xsd:enumeration value="Bremen"/>
 		<xsd:enumeration value="Hamburg"/>
 		<xsd:enumeration value="Hessen"/>
 		<xsd:enumeration value="Mecklenburg-Vorpommern"/>
 		<xsd:enumeration value="Niedersachsen"/>
 		<xsd:enumeration value="Nordrhein-Westfalen"/>
 		<xsd:enumeration value="Rheinland-Pfalz"/>
 		<xsd:enumeration value="Saarland"/>
 		<xsd:enumeration value="Sachsen"/>
 		<xsd:enumeration value="Schleswig-Holstein"/>
 		<xsd:enumeration value="Thüringen"/>
    </xsd:restriction>
</xsd:simpleType>

<xs:simpleType name="yesNoEnum">
	<xs:restriction base="xs:string">
		<xs:enumeration value="ja" />
		<xs:enumeration value="nein" />
	</xs:restriction>
</xs:simpleType>

<!-- logs
	log -->
	
<xsd:complexType name=LogsType">
	<xsd:element name="Log" type="logType">
		<xsd:complexType>
        	<xsd:attribute name="l_id" type="lIdRestriction"/> 
        </xsd:complexType>
	</xsd:element>
</xsd:complexType>

<!-- log
	gefunden_von
	gefunden_datum
	Kommentar -->
	
<xsd:complexType name="LogType">
	<xsd:sequence>
		<xsd:element name="gefundenVon" type="xsd:string">
			<xsd:complexType>
        		<xsd:attribute name="b_id" type="bIdRestriction"/> 
        	</xsd:complexType>
		</xsd:element>
		<xsd:element name="gefundenDatum" type="dateRestriction"/>
		<xsd:element name="kommentar" type="xsd:string"/>
	</xsd:sequence>
</xsd:complexType>
	
<!-- Kommentare
	kommentar -->

<xsd:complexType name="KommentareType">
	<xsd:element name="Kommentar" type="KommentarType">
		<xsd:complexType>
        	<xsd:attribute name="k_id" type="kIdRestriction"/> 
        </xsd:complexType>
	</xsd:element>
</xsd:complexType>

<!-- kommentar
	Autor
	Datum
	text -->

<xsd:complexType name="KommentarType">
	<xsd:sequence>
		<xsd:element name="Autor" type="xsd:string">
			<xsd:complexType>
        		<xsd:attribute name="b_id" type="bIdRestriction"/> 
        	</xsd:complexType>
		</xsd:element>
		<xsd:element name="Datum" type="dateRestriction"/>
		<xsd:element name="Text" type="xsd:string"/>
	</xsd:sequence>
</xsd:complexType>
	
</schema>

=== Odenthma/WBA2_P2/geocatching/src/CacheList1.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:CacheList xmlns:p="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com CacheList.xsd ">
  <p:Cache>
    <p:location lat="0.0" lon="0.0"/>
    <p:Name>p:Name</p:Name>
    <p:Datum>2001-01-01</p:Datum>
    <p:Typ>Traditional Cache</p:Typ>
    <p:Owner b_id="token">p:Owner</p:Owner>
    <p:Parkplatz lat="0.0" lon="0.0">p:Parkplatz</p:Parkplatz>
    <p:Informationen>
      <p:Schwierigkeit>1.0</p:Schwierigkeit>
      <p:Terrain>1.0</p:Terrain>
      <p:Land>p:Land</p:Land>
      <p:Bundesland>Baden-WÃ¼rttemberg</p:Bundesland>
      <p:Provinz>p:Provinz</p:Provinz>
      <p:BeschreibungKlein>p:BeschreibungKlein</p:BeschreibungKlein>
      <p:BeschreibungGross>p:BeschreibungGross</p:BeschreibungGross>
      <p:Hinweise>p:Hinweise</p:Hinweise>
      <p:GeschaetzteZeit>0.0</p:GeschaetzteZeit>
      <p:TravelBug>ja</p:TravelBug>
    </p:Informationen>
    <p:Logs>
      <p:Log l_id="token">
        <p:gefundenVon b_id="token">p:gefundenVon</p:gefundenVon>
        <p:gefundenDatum>2001-01-01</p:gefundenDatum>
        <p:kommentar>p:kommentar</p:kommentar>
      </p:Log>
    </p:Logs>
    <p:Kommentare>
      <p:Kommentar k_id="token">
        <p:Autor b_id="token">p:Autor</p:Autor>
        <p:Datum>2001-01-01</p:Datum>
        <p:Text>p:Text</p:Text>
      </p:Kommentar>
    </p:Kommentare>
  </p:Cache>
</p:CacheList>
