=== Odenthma/WBA2_P2/geocatching/src/User.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3schools.com"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">

	<xsd:element name="user" type="userType"/>

	<xsd:complexType name="userType">
	 	<xsd:sequence>
			<xsd:element name="userInformation" type="userInformationType"/>
			<xsd:element name="account" type="accountType"/>
			<xsd:element name="optional" type="optionalType"/>
		 </xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="userInformationType">
		<xsd:sequence>
			<xsd:element name="name" type="nameType"/>
			<xsd:element name="adress" type="adressType"/>
		 </xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="accountType">
		<xsd:sequence>
			<xsd:element name="logInName" type="xsd:string"/>
			<xsd:element name="logInPW" type="xsd:string"/> 
			<xsd:element name="email" type="mailRestriction"/> 
		 </xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="optionalType">
		<xsd:sequence>
			<xsd:element name="news">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute name="wanted" type="yesNoEnum" use="required"/> 
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="benachrichtigung">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute name="wanted" type="yesNoEnum" use="required"/> 
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element> 
			<xsd:element name="ortsListe" /> <!--  erweitern -->
		 </xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="nameType">
		<xsd:sequence>
			<xsd:element name="lastName" type="xsd:string"/>
			<xsd:element name="firstName" type="xsd:string"/>
		 </xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="adressType">
		<xsd:sequence>
			<xsd:element name="state" type="xsd:string"/>
			<xsd:element name="street" type="xsd:string"/>
			<xsd:element name="zipCode" type="postalRestriction"/>
			<xsd:element name="ort" type="xsd:string"/>
		 </xsd:sequence>
	</xsd:complexType>
	
<xsd:simpleType name="yesNoEnum">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="ja" />
		<xsd:enumeration value="nein" />
	</xsd:restriction>
</xsd:simpleType>
	
<xsd:simpleType name="mailRestriction">
	<xsd:restriction base="xsd:token"> 
		<xsd:pattern value="[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}"/> <!-- emailadressengÃ¼ltigkeit -->
    </xsd:restriction> 
</xsd:simpleType>	

<xsd:simpleType name="postalRestriction">
	<xsd:restriction base="xsd:token"> 
		<xsd:pattern value="[0-9]{5}"/> 
    </xsd:restriction> 
</xsd:simpleType>	
		
</xsd:schema>

=== Odenthma/WBA2_P2/geocatching/src/User1.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:user xmlns:p="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com User.xsd ">
  <p:userInformation>
    <p:name>
      <p:lastName>p:lastName</p:lastName>
      <p:firstName>p:firstName</p:firstName>
    </p:name>
    <p:adress>
      <p:state>p:state</p:state>
      <p:street>p:street</p:street>
      <p:zipCode>p:zipCode</p:zipCode>
      <p:ort>p:ort</p:ort>
    </p:adress>
  </p:userInformation>
  <p:account>
    <p:logInName>p:logInName</p:logInName>
    <p:logInPW>p:logInPW</p:logInPW>
    <p:email>token</p:email>
  </p:account>
  <p:optional>
    <p:news wanted="ja">p:news</p:news>
    <p:benachrichtigung wanted="ja">p:benachrichtigung</p:benachrichtigung>
    <p:ortsListe/>
  </p:optional>
</p:user>
